/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import sql.DBQuery;

/**
 *
 * @author Frognas
 */
public class CrearCuenta extends javax.swing.JFrame {

    DBQuery query;
    /**
     * Creates new form SignIn
     */
    public CrearCuenta() {
        initComponents();
        this.setLocationRelativeTo(null);
        query = new DBQuery();
    }

    
    public void limpiarCampos(){
        jTextUsuario.setText("");
        jTextContraseña.setText("");
        jTextContraseña2.setText("");
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRegresar = new javax.swing.JLabel();
        jLabelCrearCuenta = new javax.swing.JLabel();
        jTextUsuario = new javax.swing.JTextField();
        jTextContraseña = new javax.swing.JPasswordField();
        jTextContraseña2 = new javax.swing.JPasswordField();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jLabelContraseña2 = new javax.swing.JLabel();
        jLabelUsuario1 = new javax.swing.JLabel();
        jLabelCrearCuenta1 = new javax.swing.JLabel();
        jLabelCrearCuenta2 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar.png"))); // NOI18N
        jLabelRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegresarMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 200, 80));

        jLabelCrearCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Crearcuenta.png"))); // NOI18N
        jLabelCrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCrearCuentaMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 200, 80));

        jTextUsuario.setBackground(new java.awt.Color(0, 28, 75));
        jTextUsuario.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jTextUsuario.setBorder(null);
        getContentPane().add(jTextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 370, 30));

        jTextContraseña.setBackground(new java.awt.Color(0, 28, 75));
        jTextContraseña.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jTextContraseña.setBorder(null);
        getContentPane().add(jTextContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 370, 30));

        jTextContraseña2.setBackground(new java.awt.Color(0, 28, 75));
        jTextContraseña2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextContraseña2.setForeground(new java.awt.Color(255, 255, 255));
        jTextContraseña2.setBorder(null);
        getContentPane().add(jTextContraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 370, 30));

        jLabelUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jLabelUsuario.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuario:");
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jLabelContraseña.setBackground(new java.awt.Color(0, 0, 0));
        jLabelContraseña.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContraseña.setText("Contraseña:");
        getContentPane().add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jLabelContraseña2.setBackground(new java.awt.Color(0, 0, 0));
        jLabelContraseña2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabelContraseña2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContraseña2.setText("Confirmar contraseña:");
        getContentPane().add(jLabelContraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        jLabelUsuario1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelUsuario1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabelUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario1.setText("Crear cuenta");
        getContentPane().add(jLabelUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        jLabelCrearCuenta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Diana.png"))); // NOI18N
        getContentPane().add(jLabelCrearCuenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 100, 120));

        jLabelCrearCuenta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Archer.png"))); // NOI18N
        getContentPane().add(jLabelCrearCuenta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 310, 390));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegresarMouseClicked
        // TODO add your handling code here:
        new IniciarSesion().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelRegresarMouseClicked

    private void jLabelCrearCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCrearCuentaMouseClicked
        // TODO add your handling code here:
        if (jTextUsuario.getText().isEmpty() || jTextContraseña.getPassword().equals("") || jTextContraseña2.getPassword().equals("")) {
            JOptionPane.showMessageDialog(this, "Error: Campos no pueden estar vacios.", "Alert", JOptionPane.WARNING_MESSAGE);
        }else{
            try{
                if (new String(jTextContraseña.getPassword()).equals(new String(jTextContraseña2.getPassword())) &&
                        query.registrarUsuario(jTextUsuario.getText(), new String(jTextContraseña.getPassword()))) {
                    JOptionPane.showMessageDialog(this, "Usuario creado con exito.", "Succes", JOptionPane.INFORMATION_MESSAGE);
                    new IniciarSesion().setVisible(true);
                    this.setVisible(false);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Error al consultar la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch(SQLException e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jLabelCrearCuentaMouseClicked

   
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelContraseña2;
    private javax.swing.JLabel jLabelCrearCuenta;
    private javax.swing.JLabel jLabelCrearCuenta1;
    private javax.swing.JLabel jLabelCrearCuenta2;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelRegresar;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelUsuario1;
    private javax.swing.JPasswordField jTextContraseña;
    private javax.swing.JPasswordField jTextContraseña2;
    private javax.swing.JTextField jTextUsuario;
    // End of variables declaration//GEN-END:variables
}
