/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import entidades.Usuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Frognas
 */
public class Menu extends javax.swing.JFrame {
    
    private Usuario user;

    /**
     * Creates new form Menu
     */
    public Menu(Usuario user) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.user = user;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCerrarSesion = new javax.swing.JLabel();
        jLabelPuntaje = new javax.swing.JLabel();
        jLabelReportes = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Engranaje.png"))); // NOI18N
        jLabelCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarSesionMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 690, 100, -1));

        jLabelPuntaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Puntuacion.png"))); // NOI18N
        jLabelPuntaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPuntajeMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 370));

        jLabelReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reportes.png"))); // NOI18N
        jLabelReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelReportesMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelPuntajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPuntajeMouseClicked
        // TODO add your handling code here:
        new PuntajesMenu(user).setVisible(true);
       
    }//GEN-LAST:event_jLabelPuntajeMouseClicked

    private void jLabelCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarSesionMouseClicked
        // TODO add your handling code here:
        user = null;
        new IniciarSesion().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelCerrarSesionMouseClicked

    private void jLabelReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReportesMouseClicked
        try {
            // TODO add your handling code here:
            new ReportesMenu(user).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jLabelReportesMouseClicked

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCerrarSesion;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelPuntaje;
    private javax.swing.JLabel jLabelReportes;
    // End of variables declaration//GEN-END:variables
}
