/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import entidades.Usuario;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import sql.DBQuery;
import entidades.Ronda;

/**
 *
 * @author Frognas
 */
public class PuntajesMenu extends javax.swing.JFrame {
Usuario user;
    /**
     * Creates new form IngresarPuntajes
     */
    public PuntajesMenu(Usuario user) {
        this.user = user;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegresar = new javax.swing.JLabel();
        jComboBoxLanzamiento3 = new javax.swing.JComboBox<>();
        jComboBoxLanzamiento1 = new javax.swing.JComboBox<>();
        jComboBoxLanzamiento2 = new javax.swing.JComboBox<>();
        lblGuardar = new javax.swing.JLabel();
        jLabelInsertarPuntaje2 = new javax.swing.JLabel();
        lblTiro2 = new javax.swing.JLabel();
        lblTiro3 = new javax.swing.JLabel();
        lblTiro1 = new javax.swing.JLabel();
        lbFlecha1 = new javax.swing.JLabel();
        lbFlecha2 = new javax.swing.JLabel();
        lbFlecha3 = new javax.swing.JLabel();
        lbFlecha4 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar.png"))); // NOI18N
        lblRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegresarMouseClicked(evt);
            }
        });
        getContentPane().add(lblRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, -1, 90));

        jComboBoxLanzamiento3.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jComboBoxLanzamiento3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBoxLanzamiento3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLanzamiento3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxLanzamiento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 210, -1));

        jComboBoxLanzamiento1.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jComboBoxLanzamiento1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBoxLanzamiento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLanzamiento1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxLanzamiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 210, -1));

        jComboBoxLanzamiento2.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jComboBoxLanzamiento2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBoxLanzamiento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLanzamiento2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxLanzamiento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 210, -1));

        lblGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        lblGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGuardarMouseClicked(evt);
            }
        });
        getContentPane().add(lblGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 630, -1, 90));

        jLabelInsertarPuntaje2.setFont(new java.awt.Font("Segoe UI Historic", 0, 36)); // NOI18N
        jLabelInsertarPuntaje2.setText("Inserte su puntaje :");
        getContentPane().add(jLabelInsertarPuntaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 360, 80));

        lblTiro2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTiro2.setForeground(new java.awt.Color(255, 255, 255));
        lblTiro2.setText("2°Tiro");
        getContentPane().add(lblTiro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 90, 50));

        lblTiro3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTiro3.setForeground(new java.awt.Color(255, 255, 255));
        lblTiro3.setText("3°Tiro");
        getContentPane().add(lblTiro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 90, 50));

        lblTiro1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTiro1.setForeground(new java.awt.Color(255, 255, 255));
        lblTiro1.setText("1°Tiro");
        getContentPane().add(lblTiro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 90, 50));

        lbFlecha1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lbFlecha1.setForeground(new java.awt.Color(255, 255, 255));
        lbFlecha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Arrow.png"))); // NOI18N
        getContentPane().add(lbFlecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 200, 50));

        lbFlecha2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lbFlecha2.setForeground(new java.awt.Color(255, 255, 255));
        lbFlecha2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Arrow.png"))); // NOI18N
        getContentPane().add(lbFlecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 200, 50));

        lbFlecha3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lbFlecha3.setForeground(new java.awt.Color(255, 255, 255));
        lbFlecha3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Arrow.png"))); // NOI18N
        getContentPane().add(lbFlecha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 200, 50));

        lbFlecha4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lbFlecha4.setForeground(new java.awt.Color(255, 255, 255));
        lbFlecha4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DianaPuntos1.png"))); // NOI18N
        getContentPane().add(lbFlecha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 260, 250));

        jLabelFondo.setFont(new java.awt.Font("Segoe UI Historic", 0, 36)); // NOI18N
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresarMouseClicked
          this.setVisible(false);
    }//GEN-LAST:event_lblRegresarMouseClicked

    private void jComboBoxLanzamiento3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLanzamiento3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLanzamiento3ActionPerformed

    private void jComboBoxLanzamiento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLanzamiento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLanzamiento1ActionPerformed

    private void jComboBoxLanzamiento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLanzamiento2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLanzamiento2ActionPerformed

    private void lblGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGuardarMouseClicked
        // TODO add your handling code here:
        DBQuery query = new DBQuery();
           Ronda ronda = new Ronda();
            try{
                if (query.añadirRonda(jComboBoxLanzamiento1.getSelectedIndex(), jComboBoxLanzamiento2.getSelectedIndex(), jComboBoxLanzamiento3.getSelectedIndex())) {
                    JOptionPane.showMessageDialog(this, "Ronda agregada exitosamente!.", "Succes", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Error al consultar la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch(Exception e){
                e.printStackTrace();              
            }
    }//GEN-LAST:event_lblGuardarMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxLanzamiento1;
    private javax.swing.JComboBox<String> jComboBoxLanzamiento2;
    private javax.swing.JComboBox<String> jComboBoxLanzamiento3;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelInsertarPuntaje2;
    private javax.swing.JLabel lbFlecha1;
    private javax.swing.JLabel lbFlecha2;
    private javax.swing.JLabel lbFlecha3;
    private javax.swing.JLabel lbFlecha4;
    private javax.swing.JLabel lblGuardar;
    private javax.swing.JLabel lblRegresar;
    private javax.swing.JLabel lblTiro1;
    private javax.swing.JLabel lblTiro2;
    private javax.swing.JLabel lblTiro3;
    // End of variables declaration//GEN-END:variables
}
