/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import entidades.Ronda;
import entidades.Usuario;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import sql.DBQuery;


/**
 *
 * @author Frognas
 */
public class ReportesMenu extends javax.swing.JFrame {
    static Usuario user;
    DBQuery query ;
    
    private List<Ronda> list;
    /**
     * Creates new form Reportes
     * @throws java.sql.SQLException
     */
    public ReportesMenu(Usuario user) throws SQLException {
        System.out.println(user.getIdUsuario());
        this.user=user;
       String idUsuario= Integer.toString(user.getIdUsuario());
        initComponents();
        
        list = new ArrayList<>();
        String headers[] = {"Id Ronda","Flecha 1","Flecha 2","Flecha 3"};
        String data[][] = getData(idUsuario);
        DefaultTableModel model = new DefaultTableModel(data, headers);
        jTableRondas.setModel(model);
        
    }
    private String[][] getData(String idUsuario) throws SQLException {
        query = new DBQuery();
        list = query.Rondas(idUsuario);
        String[][] mData = new String[list.size()][5];
        
        for (int i = 0; i < mData.length; i++) {
            mData[i][0] = Integer.toString(list.get(i).getIdRonda());
            mData[i][1] = Integer.toString(list.get(i).getPuntaje1());
            mData[i][2] = Integer.toString(list.get(i).getPuntaje2());
            mData[i][3] = Integer.toString(list.get(i).getPuntaje3());
        }
        return mData;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRegresar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRondas = new javax.swing.JTable();
        jLabelResultados = new javax.swing.JLabel();
        jLabelContrats = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRegresar.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabelRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar.png"))); // NOI18N
        jLabelRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegresarMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        jTableRondas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableRondas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 510, 230));

        jLabelResultados.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabelResultados.setForeground(new java.awt.Color(255, 255, 255));
        jLabelResultados.setText("Resultados del entrenamiento:");
        getContentPane().add(jLabelResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabelContrats.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabelContrats.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContrats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Congrats.png"))); // NOI18N
        getContentPane().add(jLabelContrats, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegresarMouseClicked
        // TODO add your handling code here:
       this.setVisible(false);
    }//GEN-LAST:event_jLabelRegresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ReportesMenu(user).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ReportesMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelContrats;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelRegresar;
    private javax.swing.JLabel jLabelResultados;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableRondas;
    // End of variables declaration//GEN-END:variables
}
